### ISSUE TITLE
Unity Version 2018.3.0f2 missing

### ISSUE THREAD

**Issue by mosullivan** [DragonBox/unities#10]
2018.3 is now out of beta and so links to this should use the download.unity URL.  The latest version is 2018.3.0f2 which doesn't appear at all in the list of versions.

**Comment by niezbop** [comment]
Hey @mosullivan ! This is a known issue of u3d. [A pull request](https://github.com/DragonBox/u3d/pull/335) has been opened to fix that behaviour, and unities will get updated once the new u3d is released.

**Comment by niezbop** [comment]
I'll close the issue here, as this is related to u3d more than unities!
