### ISSUE TITLE
Unity LTS Releases not being found

### ISSUE THREAD

**Issue by KyleOrth** [DragonBox/unities#9]
Recently Unity moved over to have LTS releases (2017.4, 2018.4, etc), and three 'Tech' releases (2017.1, .2, .3).

The LTS releases are found on a separate page for download from Unity - https://unity3d.com/unity/qa/lts-releases - however the current 2017.4.0f1 and 2017.4.1f1 releases are not being loaded into the versions.json file, so u3d is unable to install them.

**Comment by lacostej** [comment]
@KyleOrth this is getting fixed right now in the cache, and will be part of u3d 1.0.21 for those not using the cache.
